version: '3.7'
services:
  postgres:
    image: postgres:13
    hostname: postgres
    container_name: nest-js-social-app-postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: social-app
